### PR TITLE
Remove the warning about threaded rendering not being optimal

### LINKED ISSUE #201: Thread engine error
**Describe the bug**
Run minimum example, linux ubuntu 24.04
The message: `"Threaded rendering is not optimal in the MapLibre Native plugin." `
If I set in main.cpp     `qputenv("QSG_RENDER_LOOP", "basic");` there will be no error, but it runs in single thread. 

**SYSTEM**
  Linux Ubuntu 24.04
 - Qt version 6.8

### PR DESCRIPTION
**Pull request by ntadej**
Remove the warning about threaded rendering not being optimal as it is just confusing people. Nowadays we can live with a slight inefficiency at the loading stage.

Closes #201.

### CODE REVIEW

**Review by louwers — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

File: src/location/qgeomap.cpp [hunk 1]
```diff
@@ -370,7 +370,7 @@ void QGeoMapMapLibrePrivate::threadedRenderingHack(QQuickWindow *window, Map *ma
     // in MapLibre Native. Meanwhile we need to set a timer to update
     // the map until all the resources are loaded, which is not exactly
     // battery friendly, because might trigger more paints than we need.
-    if (!m_warned) {
+    if (!m_threadedRenderingChecked) {
```
Comment (Ferenc-) [inline src/location/qgeomap.cpp:373]:
```suggestion
    if (!m_threadedRendering) {
```

Comment (ntadej) [reply src/location/qgeomap.cpp:373]: Hmm, this would make it check every time if threaded rendering is disabled. Not sure we want that.

**Comment by ntadej** [comment]
> Isn't `m_threadedRendering` meant to store the state of threaded rendering?

It is, but it is enough to only check once. We do not need to check multiple times if `m_threadedRendering` is still `false` after it was checked the first time.

**Comment by Ferenc-** [comment]
> > Isn't `m_threadedRendering` meant to store the state of threaded rendering?
> 
> It is, but it is enough to only check once. We do not need to check multiple times if `m_threadedRendering` is still `false` after it was checked the first time.

I agree with that part.
My observation is that having `m_threadedRenderingChecked` seems superfluous, and we could simply rely on  `m_threadedRendering` for storing the state.

**Comment by ntadej** [comment]
`m_threadedRendering` is a boolean so it can't hold three states (not checked, disabled and enabled). I think some kind of enum is an overkill for this.

But maybe we still do not understand each other?

**Comment by ntadej** [comment]
> > `m_threadedRendering` is a boolean
> 
> I know, and it's initial state is false, and it only changes after successfull checking, in essence it holds the same state as the check would.

No, as threaded rendering may be disabled 😊

**Review by birkskyum — APPROVED** [review]

**Review by Ferenc- — APPROVED** [review]
