### PR TITLE
Fix style filters setting

### LINKED ISSUE #104: setFilter documented example returns "Error parsing filter: filter operator must be a string"
src/core/map.cpp setFilter has the example:

```
        QVariantList filterExpression;
        filterExpression.push_back(QLatin1String("=="));
        filterExpression.push_back(QLatin1String("$type"));
        filterExpression.push_back(QLatin1String("Point"));

        QVariantList filter;
        filter.push_back(filterExpression);

        map->setFilter(QLatin1String("marker"), filter);
```

This returns error "Error parsing filter: filter operator must be a string".

I have tried to run in several variant list combinations and also to quote the string contents, but I always get some error.

### PR DESCRIPTION
**Pull request by ntadej**
Fix style filters setting as Qt awkwardly detects `QString` as a list so it was iterated into a list of `QChar`. Also add the following improvements:
- Add ability to remove the filter easily by setting an empty expression.
- Add a `FilterParameter` helper class.

Fixes  #104.

### CODE REVIEW

File: src/core/style/style_change.cpp [hunk 1]
```diff
@@ -49,6 +49,12 @@ std::vector<std::unique_ptr<StyleChange>> StyleChange::addParameter(const StyleP
         return changes;
     }
 
+    const auto *filterParameter = qobject_cast<const FilterParameter *>(parameter);
+    if (filterParameter != nullptr) {
+        changes.emplace_back(std::make_unique<StyleSetFilter>(filterParameter));
```
Comment (louwers) [inline src/core/style/style_change.cpp:54]: This should just be `push_back` because this is also calling a move constructor.

File: src/core/style/filter_parameter.cpp [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+    \brief A helper utility to manage filter parameters for a layer.
+    \ingroup QMapLibre
+
+    \headerfile filter_parameter.hpp <QMapLibre/FilterParameter>
+*/
+
+/*!
+    \brief Default constructor
+*/
+FilterParameter::FilterParameter(QObject *parent)
```
Comment (louwers) [inline src/core/style/filter_parameter.cpp:22]: Why does the implementation have documentation instead of the header?

Comment (ntadej) [reply src/core/style/filter_parameter.cpp:22]: This is following Qt convention.

Comment (louwers) [reply src/core/style/filter_parameter.cpp:22]: OK

File: src/core/style/filter_parameter.hpp [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+namespace QMapLibre {
+
+class Q_MAPLIBRE_CORE_EXPORT FilterParameter : public StyleParameter {
+    Q_OBJECT
+public:
+    explicit FilterParameter(QObject *parent = nullptr);
+    ~FilterParameter() override;
+
+    [[nodiscard]] QVariantList expression() const;
+    void setExpression(const QVariantList &expression);
```
Comment (louwers) [inline src/core/style/filter_parameter.hpp:25]: I feel like this could be tested a bit better. What happens if `QVariantList` is called when the list contains incompatible data types?

Comment (ntadej) [reply src/core/style/filter_parameter.hpp:25]: This is sanity-checked by the core. Added a test to make sure it does not crash.

File: src/core/style/style_change.cpp (hunk 1 above)
Comment (ntadej) [reply src/core/style/style_change.cpp]: Fixed all cases.

File: src/location/plugins/declarative_filter_parameter.hpp [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+#include "declarative_style_parameter.hpp"
+
+#include <QMapLibre/FilterParameter>
+
+#include <QtQml/QQmlEngine>
+#include <QtQml/QQmlParserStatus>
+
+namespace QMapLibre {
+
+class DeclarativeFilterParameter : public FilterParameter, public QQmlParserStatus {
```
[the remark this answers is not in the document]
Comment (ntadej) [reply src/location/plugins/declarative_filter_parameter.hpp:16]: QML is declarative language Qt uses for GUI. To make sure we do not always depend on it this class just wraps the bare C++ class and exposes it to the QML compiler.

**Review by louwers — APPROVED** [review]

**Comment by ntadej** [comment]
Will exceptionally merge this now as iOS is failing due to storage issues. As no platform-specific code is touched, this should build fine also on iOS (and does, it fails on linking).

**Comment by kebekus** [comment]
@ntadej I guess I am a little late. Still: Thanks for fixing this! I can confirm that the fix works great for my software.
